name: Deploy

# Workflow temporairement désactivé
# Pour réactiver, supprimez les commentaires ci-dessous
# on:
#   push:
#     branches: [main]
on:
  # Workflow vide (désactivé)
  workflow_dispatch:

jobs:
  deploy:
    # Condition pour empêcher l'exécution même si activé manuellement
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} 